package docs:adder@0.1.0;

world adder {
  import tarantool:tarantool/types@0.2.0;
  import tarantool:tarantool/log@0.2.0;
  import tarantool:tarantool/error@0.2.0;
  import tarantool:tarantool/key-def@0.2.0;
  import tarantool:tarantool/msgpack@0.2.0;
  import tarantool:tarantool/box-tuple@0.2.0;
  import tarantool:tarantool/tuple-format@0.2.0;
  export wasi:cli/run@0.2.3;
}
